name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install cmake & python
      run: echo Hello, world!
    - name: Checkout the tools
      run: |
        pwd
        mkdir ~/esp
        cd ~/esp
        #git clone -b branch --single-branch	git://github/repository.git
        #git clone --recursive https://github.com/espressif/esp-idf.git
        git clone --recursive -b release/v4.0 --single-branch  https://github.com/espressif/esp-idf.git
        cd ~/esp/esp-idf
        git submodule init
        git submodule update
        ./install.sh
    - name: Compile example 04
      run: |
        . $HOME/esp/esp-idf/export.sh
        export BATCH_BUILD=1
        #export V=0
        cd /home/runner/work/qemu_esp32/qemu_esp32/examples/04_sha
        idf.py build
    - name: Compile all
        cd /home/runner/work/qemu_esp32/qemu_esp32/examples
	./compile_all.sh
