name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Checkout the tools
      run: |
        pwd
        mkdir ~/esp
        cd ~/esp
        #git clone -b branch --single-branch	git://github/repository.git
        #git clone --recursive https://github.com/espressif/esp-idf.git
        git clone --recursive -b release/v4.0 --single-branch  https://github.com/espressif/esp-idf.git
        cd ~/esp/esp-idf
        git submodule init
        git submodule update
        ./install.sh
    - name: Compile example 04
      run: |
        . $HOME/esp/esp-idf/export.sh
        export BATCH_BUILD=1
        export V=0
        cd  /home/runner/work/qemu_esp32/qemu_esp32/examples/04_sha
        grep CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM *
        grep CONFIG_ESP32_WIFI_RX_BA_WIN *	
        idf.py build
        exit 1
    - name: Grep
      run: |
        grep CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM *
        grep CONFIG_ESP32_WIFI_RX_BA_WIN *	