name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Checkout the tools
      run: |
        pwd
        mkdir ~/esp
        cd ~/esp
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd ~/esp/esp-idf
        ./install.sh
    - name: Compile example 01_max_malloc
      run: |
        . $HOME/esp/esp-idf/export.sh
        export BATCH_BUILD=1
        export V=0
        cd  /home/runner/work/qemu_esp32/qemu_esp32/examples/01_max_malloc
        idf.py build
        exit 0
